export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const CHANGE_TEXTFIELD = 'CHANGE_TEXTFIELD';
export const RECEIVE_SHOPS = 'RECEIVE_SHOPS';
export const RECEIVE_SHOPS_SUCCEED = 'RECEIVE_SHOPS_SUCCEED';